### ISSUE TITLE
Add missing tests

### ISSUE THREAD

**Issue by guidomb** [Wolox/wolmo-core-ios#1]
Add missing tests for all the classes

**Comment by FranDepascuali** [comment]
There are some classes which couldn't be tested (UIKit) or were difficult to test (AVPlayer). However, https://github.com/Wolox/wolmo-core-ios/pull/18 https://github.com/Wolox/wolmo-core-ios/pull/17 https://github.com/Wolox/wolmo-core-ios/pull/15 adds lots of tests.

**Comment by danielaRiesgo** [comment]
Done for all classes that can be tested (except UIKit and AVPlayer or Bundle)
