### ISSUE TITLE
Split the framework

### ISSUE THREAD

**Issue by FranDepascuali** [Wolox/wolmo-core-ios#20]
Right now, the framework contains two functionalities: It provides extensions and utilities.

Talking with the team about this, we accorded to split the framework into different frameworks:
    1) `RACExtensions`: All the extensions or adapters we use to transform async or chained functionality into RAC (ex: NSFileManager, AVPlayer extensions)
    2) `Utilities`: The idea is to move what we have now as utilities as a framework. We also agreed that in the future, this will be discussed again, as that framework may get bigger and probably with lots of responsability. If that is the case, we'll split it again (it doesn't make sense to split it right now, as the overhead is greater than the advantage it would give right now)
    3) `Core`: Will contain what are know the extensions. It should have no dependencies.

**Comment by danielaRiesgo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split Framework](https://trello.com/c/fiwY1rLE/23-separar-framework-en-subframeworks)

**Comment by danielaRiesgo** [comment]
Solved in #102
