### ISSUE TITLE
Raise the minimum coverage level

### ISSUE THREAD

**Issue by FranDepascuali** [Wolox/wolmo-core-ios#28]
https://github.com/Wolox/wolmo-core-ios/pull/22 adds `Codestats` for coverage. The minimum coverage level should be raised to 70.

**Comment by danielaRiesgo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Card](https://trello.com/c/5pYvh9NN)

**Comment by danielaRiesgo** [comment]
Done.
