### ISSUE TITLE
Add FormTextField class to customize a textField with a colored underline

### ISSUE THREAD

**Issue by nahuelwolox** [Wolox/wolmo-core-ios#71]
https://trello.com/c/E882Zldn

**Comment by danielaRiesgo** [comment]
Shouldn't this go to https://github.com/Wolox/wolmo-utils-ios better?

**Comment by nahuelwolox** [comment]
yes I suppose it's better to add it in utils as it is a new class that you may not need

**Comment by danielaRiesgo** [comment]
Moved then.
