### ISSUE TITLE
Remove ActionHandler

### ISSUE THREAD

**Issue by adrian-ponce-wolox** [Wolox/wolmo-core-ios#78]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove ActionHandler](https://trello.com/c/ydfARmLx/29-remove-actionhandler)

RAC has a `controlEvents(.touchUpInside)` signal that I is better and more tested, than our extension. Which maybe we should remove from Core or leave it for those who doesn't use RAC

https://github.com/ReactiveCocoa/ReactiveCocoa/tree/master/Documentation
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/UIKit/UIControl.swift

**Comment by danielaRiesgo** [comment]
I agree, although it is useful for people who don't use RAC.
Take issue #9 in mind when doing this. (closing it I guess)
